# Generated by Django 3.2.16 on 2024-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=128, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Обязательное поле', max_length=128, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
