# Generated by Django 3.2.16 on 2024-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Обязательное поле', max_length=128, verbose_name='Автор рецепта')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=128, verbose_name='Название')),
                ('image', models.ImageField(help_text='Обязательное поле', upload_to='', verbose_name='Картинка')),
                ('text', models.TextField(max_length=700, verbose_name='Текстовое описание')),
                ('cooking_time', models.PositiveSmallIntegerField(default=0, help_text='Обязательное поле', verbose_name='Время приготовления в минутах')),
                ('ingredients', models.ManyToManyField(help_text='Обязательное поле', to='recipes.Ingredient', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(help_text='Обязательное поле', to='recipes.Tag', verbose_name='Теги')),
            ],
        ),
    ]
