# Generated by Django 4.2.14 on 2024-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Обязательное поле', upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
