name: testing scp and ssh capabilites

on:
  workflow_dispatch:

jobs:
  deploy_yml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copying docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: setup.cfg
          target: foodgram
          strip_components: 1

      
      
