name: testing scp and ssh capabilites

on:
  workflow_dispatch:

jobs:
  deploy_yml:
    runs-on: ubuntu-latest
    steps:
      - name: copying docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: infra/docker-compose.production.yml
          target: foodgram
          strip_components: 1

      
      
